import { IChing } from "./interface";

export const iChingNameList: IChing = {
    "乾上乾下": "乾为天",
    "坤上坤下": "坤为地",
    "坎上震下": "水雷屯",
    "艮上坎下": "山水蒙",
    "坎上乾下": "水天需",
    "乾上坎下": "天水讼",
    "坤上坎下": "地水师",
    "坎上坤下": "水地比",
    "巽上乾下": "风天小畜",
    "乾上兑下": "天泽履",
    "坤上乾下": "地天泰",
    "乾上坤下": "天地否",
    "乾上离下": "天火同人",
    "离上乾下": "火天大有",
    "坤上艮下": "地山谦",
    "震上坤下": "雷地豫",
    "兑上震下": "泽雷随",
    "艮上巽下": "山风蛊",
    "坤上兑下": "地泽临",
    "巽上坤下": "风地观",
    "离上震下": "火雷噬嗑",
    "良上离下": "山火贲",
    "良上坤下": "山地剥",
    "坤上震下": "地雷复",
    "乾上震下": "天雷无妄",
    "良上乾下": "山天大畜",
    "艮上震下": "山雷颐",
    "兑上異下": "泽风大过",
    "坎上坎下": "坎为水",
    "离上离下": "离为火",
    "兑上良下": "泽山咸",
    "震上巽下": "雷风恒",
    "乾上良下": "天山遁",
    "震上乾下": "雷天大壮",
    "离上坤下": "火地晋",
    "坤上离下": "地火明夷",
    "巽上离下": "风火家人",
    "离上兑下": "火泽睽",
    "坎上艮下": "水山蹇",
    "震上坎下": "雷水解",
    "艮上兑下": "山泽损",
    "巽上震下": "风雷益",
    "兑上乾下": "泽天夬",
    "乾上巽下": "天风姤",
    "兑上坤下": "泽地萃",
    "坤上巽下": "地风升",
    "兑上坎下": "泽水困",
    "坎上巽下": "水风井",
    "兑上离下": "泽火革",
    "离上巽下": "火风鼎",
    "震上震下": "震为雷",
    "艮上艮下": "艮为山",
    "巽上良下": "风山渐",
    "震上兑下": "雷泽归妹",
    "震上离下": "雷火丰",
    "离上艮下": "火山旅",
    "巽上巽下": "巽为风",
    "兑上兑下": "兑为泽",
    "巽上坎下": "风水涣",
    "坎上兑下": "水泽节",
    "巽上兑下": "风泽中孚",
    "震上艮下": "雷山小过",
    "坎上离下": "水火既济",
    "离上坎下": "火水未济"
}

export const iChingLinkList: IChing = {
    "乾为天": "https://www.zhouyi.cc/zhouyi/yijing64/4103.html",
    "坤为地": "https://www.zhouyi.cc/zhouyi/yijing64/4105.html",
    "水雷屯": "https://www.zhouyi.cc/zhouyi/yijing64/4106.html",
    "山水蒙": "https://www.zhouyi.cc/zhouyi/yijing64/4107.html",
    "水天需": "https://www.zhouyi.cc/zhouyi/yijing64/4108.html",
    "天水讼": "https://www.zhouyi.cc/zhouyi/yijing64/4109.html",
    "地水师": "https://www.zhouyi.cc/zhouyi/yijing64/4110.html",
    "水地比": "https://www.zhouyi.cc/zhouyi/yijing64/4111.html",
    "风天小畜": "https://www.zhouyi.cc/zhouyi/yijing64/4112.html",
    "天泽履": "https://www.zhouyi.cc/zhouyi/yijing64/4113.html",
    "地天泰": "https://www.zhouyi.cc/zhouyi/yijing64/4126.html",
    "天地否": "https://www.zhouyi.cc/zhouyi/yijing64/4127.html",
    "天火同人": "https://www.zhouyi.cc/zhouyi/yijing64/4140.html",
    "火天大有": "https://www.zhouyi.cc/zhouyi/yijing64/4141.html",
    "地山谦": "https://www.zhouyi.cc/zhouyi/yijing64/4142.html",
    "雷地豫": "https://www.zhouyi.cc/zhouyi/yijing64/4143.html",
    "泽雷随": "https://www.zhouyi.cc/zhouyi/yijing64/4144.html",
    "山风蛊": "https://www.zhouyi.cc/zhouyi/yijing64/4145.html",
    "地泽临": "https://www.zhouyi.cc/zhouyi/yijing64/4146.html",
    "风地观": "https://www.zhouyi.cc/zhouyi/yijing64/4147.html",
    "火雷噬嗑": "https://www.zhouyi.cc/zhouyi/yijing64/4148.html",
    "山火贲": "https://www.zhouyi.cc/zhouyi/yijing64/4149.html",
    "山地剥": "https://www.zhouyi.cc/zhouyi/yijing64/4150.html",
    "地雷复": "https://www.zhouyi.cc/zhouyi/yijing64/4152.html",
    "天雷无妄": "https://www.zhouyi.cc/zhouyi/yijing64/4153.html",
    "山天大畜": "https://www.zhouyi.cc/zhouyi/yijing64/4159.html",
    "山雷颐": "https://www.zhouyi.cc/zhouyi/yijing64/4164.html",
    "泽风大过": "https://www.zhouyi.cc/zhouyi/yijing64/4167.html",
    "坎为水": "https://www.zhouyi.cc/zhouyi/yijing64/4168.html",
    "离为火": "https://www.zhouyi.cc/zhouyi/yijing64/4169.html",
    "泽山咸": "https://www.zhouyi.cc/zhouyi/yijing64/4170.html",
    "雷风恒": "https://www.zhouyi.cc/zhouyi/yijing64/4171.html",
    "天山遁": "https://www.zhouyi.cc/zhouyi/yijing64/4172.html",
    "雷天大壮": "https://www.zhouyi.cc/zhouyi/yijing64/4173.html",
    "火地晋": "https://www.zhouyi.cc/zhouyi/yijing64/4174.html",
    "地火明夷": "https://www.zhouyi.cc/zhouyi/yijing64/4175.html",
    "风火家人": "https://www.zhouyi.cc/zhouyi/yijing64/4176.html",
    "火泽睽": "https://www.zhouyi.cc/zhouyi/yijing64/4177.html",
    "水山蹇": "https://www.zhouyi.cc/zhouyi/yijing64/4179.html",
    "雷水解": "https://www.zhouyi.cc/zhouyi/yijing64/4180.html",
    "山泽损": "https://www.zhouyi.cc/zhouyi/yijing64/4181.html",
    "风雷益": "https://www.zhouyi.cc/zhouyi/yijing64/4182.html",
    "泽天夬": "https://www.zhouyi.cc/zhouyi/yijing64/4183.html",
    "天风姤": "https://www.zhouyi.cc/zhouyi/yijing64/4184.html",
    "泽地萃": "https://www.zhouyi.cc/zhouyi/yijing64/4185.html",
    "地风升": "https://www.zhouyi.cc/zhouyi/yijing64/4186.html",
    "泽水困": "https://www.zhouyi.cc/zhouyi/yijing64/4187.html",
    "水风井": "https://www.zhouyi.cc/zhouyi/yijing64/4188.html",
    "泽火革": "https://www.zhouyi.cc/zhouyi/yijing64/4189.html",
    "火风鼎": "https://www.zhouyi.cc/zhouyi/yijing64/4190.html",
    "震为雷": "https://www.zhouyi.cc/zhouyi/yijing64/4192.html",
    "艮为山": "https://www.zhouyi.cc/zhouyi/yijing64/4193.html",
    "风山渐": "https://www.zhouyi.cc/zhouyi/yijing64/4194.html",
    "雷泽归妹": "https://www.zhouyi.cc/zhouyi/yijing64/4195.html",
    "雷火丰": "https://www.zhouyi.cc/zhouyi/yijing64/4196.html",
    "火山旅": "https://www.zhouyi.cc/zhouyi/yijing64/4197.html",
    "巽为风": "https://www.zhouyi.cc/zhouyi/yijing64/4198.html",
    "兑为泽": "https://www.zhouyi.cc/zhouyi/yijing64/4200.html",
    "风水涣": "https://www.zhouyi.cc/zhouyi/yijing64/4212.html",
    "水泽节": "https://www.zhouyi.cc/zhouyi/yijing64/4244.html",
    "风泽中孚": "https://www.zhouyi.cc/zhouyi/yijing64/4255.html",
    "雷山小过": "https://www.zhouyi.cc/zhouyi/yijing64/4256.html",
    "水火既济": "https://www.zhouyi.cc/zhouyi/yijing64/4257.html",
    "火水未济": "https://www.zhouyi.cc/zhouyi/yijing64/4263.html"
}


export const iChingBase = [
    { name: "坤", yaoming: ["六", "六", "六"] },
    { name: "乾", yaoming: ["九", "九", "九"] },
    { name: "兑", yaoming: ["九", "九", "六"] },
    { name: "离", yaoming: ["九", "六", "九"] },
    { name: "震", yaoming: ["九", "六", "六"] },
    { name: "巽", yaoming: ["六", "九", "九"] },
    { name: "坎", yaoming: ["六", "九", "六"] },
    { name: "艮", yaoming: ["六", "六", "九"] }
];
